# Generated by Django 4.2 on 2023-12-11 22:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('calcprojet', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
